### ISSUE TITLE
Poor performance using VirtualBox shared folders

### ISSUE THREAD

**Issue by zdennis** [lagotto/lagotto#342]
In case this helps anyone else...

VirtualBox (4.3.28) was performing really poorly when using shared folders with my host MacBook Pro. Request/responses took ~20-30 seconds and CPU utilization was around 150%.  I tried to add more CPU cores but it didn't help much. It looks like the shared folders were already using NFS when possible.

I commented out the sync folders in the `Vagrantfile` and checked out the lagotto code in its own directory. Performance is great now.

**Comment by mfenner** [comment]
Shared folder performance is a known issue with VirtualBox, and I never found a solution I was really happy with (VMWare Fusion is much better in this regard). But I'm not sure I understand where you checked out the Lagotto code. If the folder is not synced, editing becomes more complicated.

**Comment by zdennis** [comment]
Sorry for any confusion. I meant I cloned the Git repository on the virtual machine itself and set everything up there. I was curious to see where the issue lay. 

I've purchased the vmware+vagrant license (I'm a VMWare Fusion person as well) and am setting that up now.

**Comment by mfenner** [comment]
Thanks for the clarification. As this is a common Vagrant/Virtualbox issue, and you probably will not set up dozens of Vagrant instances in the coming weeks, I can probably take the time to resolve this properly. Last time I looked at this was August 2014. 

And to be clear, I mostly use Virtualbox with this setup and is reasonably fast for me.

**Comment by zdennis** [comment]
Yeah, I won't spend any more time on this. The VMWare instance running pretty well right now, so I'll just stick with this set up.
