### ISSUE TITLE
Re-Enable a disabled source

### ISSUE THREAD

**Issue by npapastefanakis** [lagotto/lagotto#423]
I think there is no way to re-enable a source when it is disabled (status 3) due to consecutive failures. If I go to the database I can do it. But in the Front end there no option for that, nor using rake according to your manual.

rake db:sources:activate                # Activate sources
rake db:sources:inactivate              # Inactivate sources
rake db:sources:install                 # Install sources
rake db:sources:uninstall               # Uninstall sources

Nikos

**Comment by mfenner** [comment]
This is intended, as for the most part there are good reasons why a source is disabled. You can do three things:

* wait. The source will re-enable if there aren't any new failures
* remove the alerts causing the source to become disabled (via `/alerts?source_id=SOURCE_NAME`)
* make the source `inactive` and then `active` again

Please use the Lagotto support forum at http://discuss.lagotto.io for these kinds of questions.

**Comment by npapastefanakis** [comment]
Thanks Martin for the quick response. 
I opened the issue in case this has been forgotten. 
Closing it.
