### ISSUE TITLE
Crossref import 404 error

### ISSUE THREAD

**Issue by npapastefanakis** [lagotto/lagotto#427]
Trying to import DOIs from crossref I receive 404 error. I installed tcpflow and I saw that the Host header passes the port => 

GET /works?filter=from-update-date%3A2010%2Cuntil-update-date%3A2015-10-21%2Cuntil-pub-date%3A2015-10-21&offset=0&rows=0 HTTP/1.1
User-Agent: Lagotto - http://lagotto.local
Accept: application/json
Host: api.crossref.org:80

This generates a 404 error to crossref.

In file var/www/lagotto/app/models/concerns/networkable.rb I added the following to test it and it worked but of course this is not the right solution (just to prove my issue):

    def faraday_conn(content_type = 'json', options = {})
        ...      
     Faraday.new do |c|
       ... 
       c.headers['Host'] = "api.crossref.org"
       ...
      end
    end

**Comment by npapastefanakis** [comment]
try the above behavior directly to crossref using curl:

curl -H "Host: api.crossref.org:80" "http://api.crossref.org/works?filter=from-update-date%3A2010%2Cuntil-update-date%3A2015-10-21%2Cuntil-pub-date%3A2015-10-21&offset=0&rows=0"

404 error returned

**Comment by mfenner** [comment]
CrossRef is migrating its REST API to a new service this week, so please expect some temporary network connectivity issues. Nothing we can do about this on the Lagotto end.

**Comment by mfenner** [comment]
@npapastefanakis I have added a Host header to the `networkable.rb` library, and that fixes my test. See referenced ticket that confirms that the missing `Host` header is the issue.
