### ISSUE TITLE
SignOut Problem 

### ISSUE THREAD

**Issue by Gauravdhandre** [lagotto/lagotto#450]
When i am SignOut from UserProfile my session is deleted steel i am SingIn Continue.

  SQL (1.3ms)  INSERT INTO `api_requests` (`uuid`, `format`, `view_duration`, `db_duration`, `duration`, `ids`, `created_at`) VALUES ('2d6eafd1-2f9f-49cd-9511-71ef764522df', 'html', 199.93923299994051, 51.210537, 251.14976999994053, 'DocsController', '2016-01-05 11:59:02')
   (57.2ms)  COMMIT
Cache delete: _session_id:2363086b04ed8f46adc4eeca6a5fab1f
Dalli::Server#connect lagotto.local:11211
lagotto.local:11211 failed (count: 21) Timeout::Error: execution expired
lagotto.local:11211 is still down (for 525.339 seconds now)
DalliError: No server available
Cache write: _session_id:911756f0dee015eb16ace419fd18a822 ({:expires_in=>86400 seconds})

**Comment by mfenner** [comment]
The problem is `DalliError: No server available`, which indicates a problem with memcached, wwhich stores the session.
