### ISSUE TITLE
why isn't this gem published on rubygems.org?

### ISSUE THREAD

**Issue by mrudult** [lagotto/lagotto#452]

**Comment by mfenner** [comment]
Can you explain? lagotto is not a Ruby gem.

**Comment by mrudult** [comment]
Sorry, my bad. I meant it for this [lagotto-gem](https://github.com/lagotto/lagotto-rb)

**Comment by mfenner** [comment]
Ok, will discuss with @sckott who wrote the lagotto-rb client.

**Comment by sckott** [comment]
that's on rubygems now, https://rubygems.org/gems/lagotto-rb
