### ISSUE TITLE
Allow deposit of relations that don't include works

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#484]
E.g. "Author has affiliation".

Not a perfect example, but relations like this should be supported. This is an argument for a 'relations' API, not a works based one.

**Comment by mfenner** [comment]
Yes and no. In the current model relations are between two different works, whereas contributions are between work and contributor, and other relations (e.g. author <-> institution) are not yet supported. The distinction makes sense to me (e.g. contributor <-> work relations can be described by CREDIT roles, i.e. using a different taxonomy), but doesn't scale so well.
