### ISSUE TITLE
Github signin prevented by unrelated Resolvable concern

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#486]
A very strange one. When logging in with Github, the `github` method on the `Resolvable` concern gets called with the wrong number of arguments. As far as I can tell they are completely unrelated. The `Resolvable` concern is not involved in the Github auth, which is an external gem.

NB in this example the Github OAuth2 is correctly configured, and commenting out the `github` method enables login.
![screen shot 2016-03-04 at 12 21 33](https://cloud.githubusercontent.com/assets/389345/13527123/b836c58c-e204-11e5-83dc-59c23e79f0e8.png)

**Comment by mfenner** [comment]
This is indeed a namespace clash with the `github` method in the `resolvable` concern. That method was recently added as part of the agent refactoring. Renaming the method (to `github_repo`) fixes the authentication issue.
