### ISSUE TITLE
Is it necessary to register a source before pushing?

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#487]
Can a deposit be processed if the source-id is previously unknown to Lagotto? Is it necessary to register it first?

**Comment by mfenner** [comment]
It would make matters complicated if sources could be generated on the fly. Maybe we should discuss the use case.

One important change in newer deposit code: an error will be raised if the source doesn't exist.

**Comment by mfenner** [comment]
Closing this for now.
