### ISSUE TITLE
Relations contain subject metadata

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#508]
I think it's a bit arbitrary that the relation contains the metadata of the subject. I would expect just the data of the Relation, not the joined Work, i.e. `subj_id`, `obj_id`, `source_id`, `relation_type_id`, `total`, `timestamp`. 

Surely the title etc of one of the items in the relation doesn't belong there?

**Comment by mfenner** [comment]
The metadata of the subject is included so that only one API call is required to show all relations per work. We can discuss the API format going format, as you know I like JSONAPI, which would use side-loading here.
