### ISSUE TITLE
Some DOIs don't have a title in the metadata. Lagotto can't deal with this.

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#515]
E.g. http://api.crossref.org/works/10.1023/A:1004636609126

I suggest automatically setting the title to the DOI if no title can be retrieved. The alternative is missing works.

**Comment by mfenner** [comment]
There has been a longer discussion on this topic last year. The current implementation checks whether the title is required for that particular item type (as is the case for the article above). If that is not the case lagotto falls back to `No title`. @kjw might have a suggestion.

The code for this is here: https://github.com/lagotto/lagotto/blob/5-0-unstable/app/models/concerns/resolvable.rb#L165-L173 and it also covers some edge cases (e.g. if first element in title array is blank).

**Comment by mfenner** [comment]
DataCite has a standard list of unknown values for its metadata schema (from http://doi.org/10.5438/0010):

* (:unac): temporarily inaccessible
* (:unal): unallowed, suppressed intentionally
* (:unap): not applicable, makes no sense
* (:unas): value unassigned (e.g., Untitled)
* (:unav): value unavailable, possibly unknown
* (:unkn): known to be unknown (e.g., Anonymous, Inconnue)
* (:none): never had a value, never will
* (:null): explicitly and meaningfully empty
* (:tba): to be assigned or announced later
* (:etal) too numerous to list (et alia)

I think we have to be very careful with assigning values when a required field is missing. Maybe using an appropriate value from this list (e.g. `(:unas)`) makes sense when the title is required but missing.
