### ISSUE TITLE
"Events" is confusing, should be "totals"

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#517]
Using the word 'Events' is misleading as it's the total number of relations not the total number of events (e.g. adds deletes).

**Comment by mfenner** [comment]
I disagree, as there is no commonly agreed definition for 'Events'. I think this needs a broader discussion.

**Comment by afandian** [comment]
Indeed. 

We decided on the name 'Crossref Event Data' and in doing so we (informally) defined the word Event in our messaging and outreach. We're defining Event as something like "activity that occurs around a DOI", e.g. the removal of a citation.

Lagotto currently defines an Event as an aggregation of relation counts, not e.g. "a DOI reference was removed from Wikipedia". Using it differently in the Lagotto UI and in our service name would be confusing.

We'd much prefer 'Total' or 'Aggregations' and it does describe what the aggregations actually are.
