### ISSUE TITLE
how should `q` parameter be used?

### ISSUE THREAD

**Issue by sckott** [lagotto/lagotto#546]
not seen any examples of it's use - the docs https://github.com/lagotto/lagotto/blob/master/app/controllers/api/v7/works_controller.rb#L14 say 

> Query for ids

Query with what? A work identifier? What does a value passed to `q` do in the backend?  Perhaps a sql `like` query on the identifier column?

**Comment by afandian** [comment]
Agreed, I think that was left over from the previous version.

**Comment by mfenner** [comment]
Needs to be documented, but it means that you can use any of the following:
- pid
- doi
- pmid
- url
- wos
- scp
- arxiv
- ark

If you don't provide a `pid`, use `type`to specify the kind of id. This behaviour has not changed from previous Lagotto versions.

**Comment by mfenner** [comment]
Example: http://api.eventdata.crossref.org/api/works?ids=10.1038/NATURE17946,10.1002/14651858.CD005220.PUB2&type=doi

Could also be written as: http://api.eventdata.crossref.org/api/works?ids=http://doi.org/10.1038/NATURE17946,http://doi.org/10.1002/14651858.CD005220.PUB2

**Comment by sckott** [comment]
Thanks for the clarification, your eg doesn't use the `q` parameter though - so this http://api.eventdata.crossref.org/api/works?q=10.1038/NATURE17946&type=doi works - couldn't do two identifiers though

**Comment by mfenner** [comment]
The `q` parameter is currently not very useful, the reason is that a fuzzy query using `LIKE` is too expensive with many works. Therefore `q` currently only supports lookup by DOI, which can also be done via `ids` parameter. This therefore also works: http://api.eventdata.crossref.org/api/works?q=10.1038/NATURE17946. The main use case right now is lookup of a single work via the UI.

**Comment by mfenner** [comment]
We hopefully have a solution in the coming months that allows more complex queries.

**Comment by sckott** [comment]
Okay, thanks for further clarification
