### ISSUE TITLE
Unable to login in lagotto 5.0.1

### ISSUE THREAD

**Issue by Gauravdhandre** [lagotto/lagotto#579]
Please tolled me how to get loging in lagotto 5.0.1, i am suffering from this issue..
please help me!

**Comment by mfenner** [comment]
Have you successfully installed Lagotto 5.0.1? You need to configure third-party authentication with GitHub, ORCID, or jwt.

**Comment by Gauravdhandre** [comment]
I am added authentication of ORCID as well as GitHub in .env File steel not able to login..When click on Sign in Button it render me to error page..
I am new in rails please help me..

**Comment by Gauravdhandre** [comment]
![loggind](https://cloud.githubusercontent.com/assets/16300277/15179754/5fbca102-179b-11e6-826f-69c4ee71d60a.png)

**Comment by Gauravdhandre** [comment]
When SignIn with Orcid it gives "Please check your client id and redirect URIs." message
![orcidnew](https://cloud.githubusercontent.com/assets/16300277/15180554/f0851184-179f-11e6-8239-15d9f3c119f1.png)

**Comment by Gauravdhandre** [comment]
Sorry for disturbance it working fine...
Thank you ...

**Comment by mfenner** [comment]
Excellent!
