### ISSUE TITLE
ActionView::MissingTemplate in docs#index

### ISSUE THREAD

**Issue by mfenner** [lagotto/lagotto#597]
## Error in Event Data Backend

**ActionView::MissingTemplate** in **docs#index**
Missing template docs/show, application/show with {:locale=>[:en], :formats=>[:gif, "image/x-xbitmap", :jpeg, "image/pjpeg", "application/x-shockwave-flash", "application/vnd.ms-excel", "application/vnd.ms-powerpoint", "application/msword"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
- "/var/www/lagotto/app/views"
- "/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/swagger-ui_rails-0.1.7/app/views"
- "/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/app/views"

[View on Bugsnag](https://bugsnag.com/datacite/event-data-backend/errors/574e3c30be3f29e6a61eb0f7?event_id=574e3c312c4ac15644bdb997)
## Stacktrace

```
app/controllers/docs_controller.rb:5 - index
```

[View full stacktrace](https://bugsnag.com/datacite/event-data-backend/errors/574e3c30be3f29e6a61eb0f7?event_id=574e3c312c4ac15644bdb997)

**Comment by jimneath** [comment]
I'm seeing this issue also
