### ISSUE TITLE
Single-table inheritance issue

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#612]
Logged in shows error on http://api.eventdata.crossref.org/agents

> The single-table inheritance mechanism failed to locate the subclass: 'Datacite'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Agent.inheritance_column to use another column for that information.

**Comment by mfenner** [comment]
This was caused by an entry in the `agents` table without a corresponding agent subclass. There is currently no mechanism to automatically remove database entries for classes that have been removed (`datacite`, `datacite_data`).
