### ISSUE TITLE
uninitialized constant LogStashLogger

### ISSUE THREAD

**Issue by imyawar** [lagotto/lagotto#623]
I enabled the config "LOGSTASH_PATH=log/agent.log". I am getting an error while executing `bundle exec rake queue:all`

Error log:
rake aborted!
NameError: uninitialized constant LogStashLogger
/var/www/lagotto/config/initializers/logstash.rb:10:in `<top (required)>'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in`block in load_config_initializer'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in`load_config_initializer'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in`each'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`instance_exec'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in`block in run_initializers'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in`tsort_each_child'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in`initialize!'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in`method_missing'
/var/www/lagotto/config/environment.rb:5:in `<top (required)>'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:328:in`require_environment!'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/www/lagotto/vendor/bundle/ruby/2.2.0/gems/bugsnag-2.8.13/lib/bugsnag/rake.rb:12:in`execute_with_bugsnag'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in`kernel_load'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in`exec'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in`invoke_command'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in`start'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in`block in <top (required)>'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in`<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in`<main>'
Tasks: TOP => queue:all => environment

logstash-logger is already installed through # gem install logstash-logger

Is there any other config which am I missing?

**Comment by mfenner** [comment]
This functionality is no longer supported in Lagotto 5 because of major architectural changes. We will implement similar functionality going forward.
