### ISSUE TITLE
Facebook API works with DOIs

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#630]
The Facebook agent uses landing pages to query Facebook. However, Facebook seems to work with DOIs, doing the link-following itself. e.g.:

https://graph.facebook.com/v2.1/?access_token=XXX|XXX&id=http://doi.org/10.1056/NEJMOA1512610

`{
og_object: {
id: "798074036987320",
description: "Original Article from The New England Journal of Medicine — Sofosbuvir and Velpatasvir for HCV Genotype 1, 2, 4, 5, and 6 Infection",
title: "NEJM",
type: "article",
updated_time: "2016-08-08T18:26:56+0000"
},
share: {
comment_count: 0,
share_count: 2936
},
id: "http://doi.org/10.1056/NEJMOA1512610"
}`

https://graph.facebook.com/v2.1/?access_token=XXX|XXX&id=http://www.nejm.org/doi/10.1056/NEJMoa1512610

`{
og_object: {
id: "798074036987320",
description: "Original Article from The New England Journal of Medicine — Sofosbuvir and Velpatasvir for HCV Genotype 1, 2, 4, 5, and 6 Infection",
title: "NEJM",
type: "article",
updated_time: "2016-08-08T18:26:56+0000"
},
share: {
comment_count: 0,
share_count: 2936
},
id: "http://www.nejm.org/doi/10.1056/NEJMoa1512610"
}`

Maybe Facebook changed the API since it was developed? Removing landing page reversal would simplify the agent.

**Comment by mfenner** [comment]
There is a long history behind it. The short version is that Facebook can only use DOIs if it correctly resolves to a landing page. In good percentage of cases (maybe 10-20% of Crossref DOIs) that is not happening. Collecting the landing page URL is one way to ensure that we get the correct numbers.

**Comment by afandian** [comment]
I knew there was some kind of story. Not entirely sure I understand though.

Do we know if there is ever any Facebook activity when the DOI doesn't resolve to a landing page? Surely if a DOI doesn't resolve to a landing then it can't be shared on FB?

**Comment by afandian** [comment]
I've looked into this quite thoroughly. I'm working out how to work with the diverse range of landing page behaviours that Crossref DOIs resolve to. I'm looking into a more centralised way of solving this.
